version: '3.3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3002:3000'
        environment:
            - GQL_API_DOMAIN_BACKEND=http://localhost:3000
        volumes:
            - .:/app
